#!/bin/bash
#
# Installs and configures Wazuh agent on linux.
#
# Copyright (C) 2020  Peter Zendzian <zendzipr@gmail.com>
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Usage
# bash <(curl -s https://raw.githubusercontent.com/zendzipr/linux-system-administrator/master/setup)
# bash <(curl -s https://raw.githubusercontent.com/zendzipr/linux-system-administrator/branch/setup) branch


url="https://raw.githubusercontent.com/zendzipr/linux-system-administrator/"

if [[ -z "$1" ]]; then
  branch=master
else
  branch=$1
fi

# Make sure only root can run script
if [[ $EUID -ne 0 ]]; then
  echo "Permission Denied"
  echo "Root privileges required" 1>&2
  exit 1
fi

source <(curl -s "${url}${branch,,}"/lib/common)

if [[ -z $ver ]]; then
  echo ERROR: unable to load libraries
  exit 1
fi

menu=""
until [[ "$menu" = "7" ]]; do

  clear
  banner

  if is_package_installed wazuh-agent > /dev/null 2> /dev/null; then
      is_wazuh_agent_installed="(Installed)"
  fi

  if [[ -z $(realm list -n --unattended 2> /dev/null) ]]; then
      echo "1. Join Active Directory Domain"
  else
      echo "1. Configure Domain Services"
  fi

  if is_package_installed ntp; then
      echo "2. Configure Time Services"
  else
      echo "2. Install Time Services"
  fi

  if is_package_installed wazuh-agent; then
      echo "3. Configure Wazuh"
  else
      echo "3. Install Wazuh"
  fi
  echo "4. System Configuration"

  if is_package_installed zabbix-agent; then
      echo "5. Configure Zabbix Agent"
  else
      echo "5. Install Zabbix Agent"
  fi

  echo "7. Exit"
  echo

  read menu
  case ${menu} in

    1)
      bin_loader ${url} ${branch} joindomain
      ;;
    2)
      bin_loader ${url} ${branch} ntp
      ;;

    3)
      bin_loader ${url} ${branch} wazuh_agent
      ;;
    4)
      bin_loader ${url} ${branch} settings
      ;;
    5)
      bin_loader ${url} ${branch} zabbix_agent
      ;;
    8)
      break
      ;;

    *) ;;
  esac
done