#!/bin/bash

# Linux System Administrator.
#
# Copyright (C) 2020  Peter Zendzian <zendzipr@gmail.com>
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

if [[ $EUID -ne 0 ]]; then
  echo "Permission Denied"
  echo "Root privileges required" 1>&2
  exit 1
fi

## Set Variables
ntp="ntpd"

## Package management
function is_package_installed () {
  yum list installed $1 &> /dev/null 2>&1
}

function package_install () {
  yum install -y $1 > /dev/null 2> /dev/null
}

function package_remove () {
  yum remove -y $1 > /dev/null 2> /dev/null
}

function package_unhold () {
    :
}